-- QR Event Information System
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  qr_code text not null unique,
  name text not null,
  position text default '',
  organization text default '',
  message text default '',
  photo_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  scanned_at timestamptz not null default now(),
  scanner_name text default ''
);

create index if not exists participants_qr_code_idx on public.participants(qr_code);
create index if not exists scan_history_scanned_at_idx on public.scan_history(scanned_at desc);

alter table public.participants enable row level security;
alter table public.scan_history enable row level security;

-- EVENT PROTOTYPE POLICIES:
-- These allow the GitHub Pages browser app to operate without login.
-- For a public production deployment, add Supabase Auth and replace these
-- policies with authenticated admin policies.

drop policy if exists "public read participants" on public.participants;
create policy "public read participants"
on public.participants for select
to anon, authenticated
using (true);

drop policy if exists "public insert participants" on public.participants;
create policy "public insert participants"
on public.participants for insert
to anon, authenticated
with check (true);

drop policy if exists "public update participants" on public.participants;
create policy "public update participants"
on public.participants for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read scans" on public.scan_history;
create policy "public read scans"
on public.scan_history for select
to anon, authenticated
using (true);

drop policy if exists "public insert scans" on public.scan_history;
create policy "public insert scans"
on public.scan_history for insert
to anon, authenticated
with check (true);

-- Storage bucket for participant photos.
insert into storage.buckets (id, name, public)
values ('participant-photos', 'participant-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "public upload participant photos" on storage.objects;
create policy "public upload participant photos"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'participant-photos');

drop policy if exists "public view participant photos" on storage.objects;
create policy "public view participant photos"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'participant-photos');

drop policy if exists "public update participant photos" on storage.objects;
create policy "public update participant photos"
on storage.objects for update
to anon, authenticated
using (bucket_id = 'participant-photos')
with check (bucket_id = 'participant-photos');

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists participants_updated_at on public.participants;
create trigger participants_updated_at
before update on public.participants
for each row execute function public.set_updated_at();
